[package]
name = "easy_ffmpeg"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "ffmpeg command box"
homepage = "https://www.bjcs.info"
documentation = "https://www.bjcs.info"
repository = ""
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
